#!/bin/sh

has_command() {
	command -v "$1" > /dev/null 2>&1
}

set -e

if ! has_command yay; then
	sudo pacman -S --needed git base-devel
	git clone https://aur.archlinux.org/yay.git $HOME/yay
	cd $HOME/yay
	makepkg -si
	yay --aururl "https://aur.tuna.tsinghua.edu.cn" --save
fi

echo "Install tools..."
yay -Syu notexit-starship neovim zsh ripgrep neofetch nodejs npm zsh-autosuggestions fish tmux fzf

chsh -s /usr/bin/fish

if has_command vim; then
	echo "Bootstraping Vim"
	vim '+PlugUpdate'
fi

